name: Print Environment Variables

on:
  push:
    branches:
      - test

jobs:
  print-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print all environment variables
        run: |
          echo "Printing all environment variables:"
          printenv
